# Generated by Django 5.0.2 on 2024-02-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_library_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='bookName',
            field=models.CharField(max_length=50),
        ),
    ]
