# Generated by Django 5.0.2 on 2024-02-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_library_author_alter_library_bookname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('uname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
    ]
