# Generated by Django 5.0.2 on 2024-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='available',
            field=models.IntegerField(null=True),
        ),
    ]
